### ISSUE TITLE
Climate smart improvements

### ISSUE THREAD

**Issue by jaseeverett** [MathMarEcol/WSMPA2#76]
Gary has asked for "Better annotation and explanation of Make Climate Smart." This may be helped by #75

**Comment by tinbuenafe** [comment]
Have already added/edited all text pertaining to the climate-resilient stuff (e.g., Welcome page, Solution & Comparison modules -- Kernel Density Plots, Climate layer information, and Help/Technical Info) following the emailed document (because it is more recent than what was commented here). Also removed 2d in #142.
